### ISSUE TITLE
The module is out of date, please update

### ISSUE THREAD

**Issue by vanjacosic** [mafintosh/are-feross-and-mafintosh-stuck-in-an-elevator#1]
@mafintosh and @feross are no longer stuck in the elevator, which means the module is no longer returning accurate data. Please updata it asap! :grin:

**Comment by valberg** [comment]
This issue is out of date!

**Comment by LinusU** [comment]
Fixed by 47709e192285a92923d024f19b31813cd59ddce2 :+1:

**Comment by vanjacosic** [comment]
Haha, thanks for the quick update! Closing :laughing:
