### ISSUE TITLE
Compatibility with Safari?

### ISSUE THREAD

**Issue by klaemo** [mafintosh/are-feross-and-mafintosh-stuck-in-an-elevator#9]
Is this module compatible with Safari! I've heard it's the new IE.

**Comment by LinusU** [comment]
Absolutely!

![screen shot 2015-08-05 at 17 36 32](https://cloud.githubusercontent.com/assets/189580/9090038/81b13366-3b98-11e5-9f28-ec9411557727.png)

**Comment by mafintosh** [comment]
@LinusU if you send me a pr for browser support i'll merge it.

**Comment by LinusU** [comment]
It's compatible out of the box with browserify, it just worked :cocktail: 

Do you think that we should provide a stand-alone browser build?

**Comment by mafintosh** [comment]
@LinusU yes and a build script as a npm script (plus that browser table above)

**Comment by LinusU** [comment]
This should be closed by #12
